language: python

python:
  - "3.6"
  - "3.7"

os:
  - linux

before_install:
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-4
  - sudo apt-get -y install ffmpeg
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install .

script:
  - cd test && python -m unittest discover .