language: python

python:
  - "3.6"
  - "3.7"

os:
  - linux

before_install:
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -y
  - sudo apt-get update
  - sudo apt-get -y install ffmpeg
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install coverage
  - pip install .

script:
  - ffmpeg -version
  - cd test && coverage run -m unittest discover .

after_success:
  - bash <(curl -s https://codecov.io/bash)