language: python

python:
  - "3.6"
  - "3.7"

os:
  - linux

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install .

script:
  - cd test && python -m unittest discover .